### ISSUE TITLE
Reconnect attempts cause gRPC ManagedChannels to be orphaned

### ISSUE THREAD

**Issue by dpasek-senacor** [EventStore/EventStoreDB-Client-Java#163]
The reconnection attempts of the `GrpcClient` will orphan the previously created `ManagedChannel` when creating the new channel. This will cause exception logs like:
```
09:43:22,843 |- ERROR in io.grpc.internal.ManagedChannelOrphanWrapper - *~*~*~ Channel ManagedChannelImpl{logId=32, target=localhost:2113} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true. -| java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
	at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:630)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:297)
	at com.eventstore.dbclient.GrpcClient.createChannel(GrpcClient.java:322)
	at com.eventstore.dbclient.SingleNodeClient.doConnect(SingleNodeClient.java:21)
	at com.eventstore.dbclient.GrpcClient.discover(GrpcClient.java:158)
	at com.eventstore.dbclient.GrpcClient.handleMsg(GrpcClient.java:207)
	at com.eventstore.dbclient.GrpcClient.messageLoop(GrpcClient.java:259)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
``` 
The gRPC implementation tracks channel creation internally by the `ManagedChannelOrphanWrapper` and will log this error if a channel instance is garbage collected without being properly shutdown beforehand.
This actually will not the connection retry of ES client to break but clutters the log files and shows an error in the implementation as all channels should properly be shutdown and all resources released before being garbage collected.

**Comment by dpasek-senacor** [comment]
PR available:
https://github.com/EventStore/EventStoreDB-Client-Java/pull/164
