### ISSUE TITLE
Getting io.grpc.StatusRuntimeException: PERMISSION_DENIED: Access Denied for EventStoreDBPersistentSubscriptionsClient

### ISSUE THREAD

**Issue by dhirajkumar94** [EventStore/EventStoreDB-Client-Java#56]
Hi,

I am trying to create a persistent subscription to a stream using EventStoreDBPersistentSubscriptionsClient, but it's throwing the exception `io.grpc.StatusRuntimeException: PERMISSION_DENIED: Access Denied`.

My code:

```
EventStoreDBClientSettings settings = new ConnectionSettingsBuilder()
                .addHost(new Endpoint(config.getHost(), config.getPort()))
                .defaultCredentials(config.getUsername(), config.getPassword())
                .tls(config.isTls())
                .nodePreference(NodePreference.LEADER)
                .buildConnectionSettings();

EventStoreDBPersistentSubscriptionsClient persistentSubsClient = EventStoreDBPersistentSubscriptionsClient.create(settings);

PersistentSubscriptionSettings persistenceSettings = PersistentSubscriptionSettings.builder().resolveLinks(true)
                .enableExtraStatistics()
                .enableLinkResolution()
                .maxRetryCount(100)
                .build();

CreatePersistentSubscriptionOptions createOptions = CreatePersistentSubscriptionOptions.get().settings(persistenceSettings)
                .authenticated(credentials);
persistentSubsClient.create(streamName, group, createOptions).get();
```

I am also using EventStoreDBClient which is connecting successfully to the server using the following code:

```
EventStoreDBClientSettings settings = new ConnectionSettingsBuilder()
                .addHost(new Endpoint(config.getHost(), config.getPort()))
                .defaultCredentials(config.getUsername(), config.getPassword())
                .tls(config.isTls())
                .nodePreference(NodePreference.LEADER)
                .buildConnectionSettings();
EventStoreDBClient storeDBClient = EventStoreDBClient.create(settings);

CompletableFuture<WriteResult> completableFuture = storeDBClient.appendToStream(streamName, event);

List<ResolvedEvent> resolvedEvents = storeDBClient.readStream(streamName, 100, options).get().getEvents();
```

StackTrace:
```
io.grpc.StatusRuntimeException: PERMISSION_DENIED: Access Denied
	at io.grpc.StatusRuntimeException.fillInStackTrace(StatusRuntimeException.java:68)
	at io.grpc.StatusRuntimeException.<init>(StatusRuntimeException.java:58)
	at io.grpc.StatusRuntimeException.<init>(StatusRuntimeException.java:50)
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:617)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:803)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:782)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

I'm using the following dependency:

```
<dependency>
            <groupId>com.eventstore</groupId>
            <artifactId>db-client-java</artifactId>
            <version>0.6</version>
</dependency>
```

**Comment by YoEight** [comment]
This is expected behaviour if you try to create a persistent subscription and the logged user doesn't have an admin role.

**Comment by dhirajkumar94** [comment]
@YoEight I'm using admin user credentials

**Comment by YoEight** [comment]
According to your code, when creating your persistent subscription, you use a default credentials and another credentials at the command level. In both cases, are you using the same credentials?

**Comment by dhirajkumar94** [comment]
@YoEight yes, I'm using the same credentials.

Do I need to pass the credentials at the command level or just passing the PersistentSubscriptionSettings will work?

**Comment by YoEight** [comment]
I would recommend using credentials at the command level to only override whatever configuration you have globally.

What is the stream you try to create a persistent subscription on?
Are you sure you entered the credentials correctly?
What version of the server you are using?

**Comment by dhirajkumar94** [comment]
@YoEight We are creating our own stream.
Yes, I'm entering the correct credentials.
We're using server version 20.6.1.0

**Comment by YoEight** [comment]
I'm unable to reproduce this behaviour but I still got questions.

When you try to create your persistent subscription, do you see a line in the server log resembling something like this:

```
Failed authorization check for {identity} in {duration} with {evaluationResult}
```
?

Did you change the default ACLs in your cluster?

When creating a persistent subscription, the authenticated user needs to also have read access on the target stream.
