### ISSUE TITLE
What to do when onError and onCancelled happens

### ISSUE THREAD

**Issue by huyhoangepay** [EventStore/EventStoreDB-Client-Java#80]
We have a persistent subscription. Every once in a while the `PersistentSubscriptionListener` gets disconnected from the server. Log:
```
io.grpc.StatusRuntimeException: UNAVAILABLE: Keepalive failed. The connection is likely gone
        at io.grpc.Status.asRuntimeException(Status.java:533) ~[grpc-api-1.31.1.jar!/:1.31.1]
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478) ~[grpc-stub-1.31.1.jar!/:1.31.1]
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:434) ~[grpc-core-1.31.1.jar!/:1.31.1]
        at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66) ~[grpc-core-1.31.1.jar!/:1.31.1]
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:763) ~[grpc-core-1.31.1.jar!/:1.31.1]
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:742) ~[grpc-core-1.31.1.jar!/:1.31.1]
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.31.1.jar!/:1.31.1]
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[grpc-core-1.31.1.jar!/:1.31.1]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```
I have a couple of question:
* Is there any reason why the connection gets dropped?
* What should we do in this scenario? Do we need to manually re-subscribe to the server?

**Comment by YoEight** [comment]
It's a classic case of gRPC closing the connection because of inactivity. It's the gRPC built-in heartbeat protocol in action. The client allows you to configure this behaviour through two parameters:

`keepAliveInterval`:  How long the connection should wait if no message is coming through before asking for a heartbeat. (10s by default)
`keepAliveTimeout`: How long the connection should wait without receiving a heartbeat response. (10s by default)

In the case of (persistent) subscriptions, we recommend disabling the keep-alive feature. You can achieve that by assigning both properties to `-1`.

For any other case, I can't recommend just reconnect automatically. There is no guarantee you will only get EventStoreDB related exceptions, it's Java after all. Having said that, there is no harm keeping reconnecting when an error is raised.

**Comment by huyhoangepay** [comment]
@YoEight thanks for the response.   
Is there any sample code for how we should re-subscribe?  
What I'm not sure about is:
* Do we re-subscribe in `onError` or `onCancelled`?
* If `onError`, what is the `Throwable` we should catch to re-subscribe?

**Comment by YoEight** [comment]
> Do we re-subscribe in `onError` or `onCancelled`?

I don't know, it depends on the application. Based on my own experience, I rather have an application that consumes a persistent subscription to die in case of any exception. I would let the application manager restarting that app for me.

> If onError, what is the Throwable we should catch to re-subscribe?

The `Throwable` instance would be the exception that caused the subscription to terminate. Should you re-subscribe here? I personally won't but doing that won't prevent the client from working correctly.
