### ISSUE TITLE
Error when creating persistent subscription on cloud cluster

### ISSUE THREAD

**Issue by huyhoangepay** [EventStore/EventStoreDB-Client-Java#81]
Hi, we're using ES cloud with a 3-node cluster.
The connection string is the DNS with discovery `esdb+discover://`
When we try to call `EventStoreDBPersistentSubscriptionsClient.create()` we get this error.
```
com.eventstore.dbclient.NotLeaderException: null
	at com.eventstore.dbclient.GrpcUtils$1.onError(GrpcUtils.java:49) ~[db-client-java-1.0.0.jar:na]
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:460) ~[grpc-stub-1.30.2.jar:1.30.2]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426) ~[grpc-core-1.30.2.jar:1.30.2]
	at io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66) ~[grpc-core-1.30.2.jar:1.30.2]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689) ~[grpc-core-1.30.2.jar:1.30.2]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577) ~[grpc-core-1.30.2.jar:1.30.2]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751) ~[grpc-core-1.30.2.jar:1.30.2]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740) ~[grpc-core-1.30.2.jar:1.30.2]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.30.2.jar:1.30.2]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[grpc-core-1.30.2.jar:1.30.2]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]
```
I tried doing the same thing with the .NET Grpc client and this error did NOT occur.
Also, we have 2 clusters and this error only happens with one of them (the code used is the same).
If  I change the connection string to point to the leader node rather than the cluster's DNS, I was able to create the subscription group.

### More debugging information
I did some debugging and found that this code throws the exception: https://github.com/EventStore/EventStoreDB-Client-Java/blob/trunk/db-client-java/src/main/java/com/eventstore/dbclient/GrpcUtils.java#L48 . The client received the following message: `io.grpc.StatusRuntimeException: NOT_FOUND: Leader info available`. The leader address (`leaderHost` and `leaderPort`) can be resolved, but the client throws an exception anyway.

So my questions are:
* Why would this NOT_FOUND message occur?
* If the leader is found, shouldn't the client re-direct the message to that leader?
* How do we resolve this issue?

**Comment by YoEight** [comment]
It seems you didn't connect to the leader of your cluster when you try to connect. If you retry right away when it happens, it should work as the client already connected to the provided leader node. In your connection string, do you have `nodePreference=leader` ? If not, having that setting will prevent having that exception in the first place when interacting with persistent subscriptions.

**Comment by phongnguyen-monex** [comment]
Adding nodePreference=leader resolved our issues. Thanks
